[package]
name = "AdventOfCode-2021"
version = "0.1.0"
authors = ["hesamzkr <hesam.zk.81@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
